/* Generated By:JJTree: Do not edit this line. AnnotationMethodOrConstantRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class AnnotationMethodOrConstantRest extends SimpleNode {
  public AnnotationMethodOrConstantRest(int id) {
    super(id);
  }

  public AnnotationMethodOrConstantRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=52e1595d53b03e47c1802e3796b1023c (do not edit this line) */
