/* Generated By:JJTree: Do not edit this line. AnnotationTypeElementDeclarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class AnnotationTypeElementDeclarations extends SimpleNode {
  public AnnotationTypeElementDeclarations(int id) {
    super(id);
  }

  public AnnotationTypeElementDeclarations(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ed307e38427a137475b5f7739035dfb2 (do not edit this line) */
