/* Generated By:JJTree: Do not edit this line. AnnotationMethodRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class AnnotationMethodRest extends SimpleNode {
  public AnnotationMethodRest(int id) {
    super(id);
  }

  public AnnotationMethodRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0dd15b5b56b2ac37d764196055e0574a (do not edit this line) */
