/* Generated By:JJTree: Do not edit this line. AnnotationTypeElementRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class AnnotationTypeElementRest extends SimpleNode {
  public AnnotationTypeElementRest(int id) {
    super(id);
  }

  public AnnotationTypeElementRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=929a9b6233c30c7c6527abe85bcd5be8 (do not edit this line) */
