/* Generated By:JJTree: Do not edit this line. AnnotationTypeDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class AnnotationTypeDeclaration extends SimpleNode {
  public AnnotationTypeDeclaration(int id) {
    super(id);
  }

  public AnnotationTypeDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ccedecaccc4a70ebd41dd632fc3e6959 (do not edit this line) */
