/* Generated By:JJTree: Do not edit this line. ConstructorDeclaratorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class ConstructorDeclaratorRest extends SimpleNode {
  public ConstructorDeclaratorRest(int id) {
    super(id);
  }

  public ConstructorDeclaratorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=09fc49e1681a2ec4b0c13e4be5379c9c (do not edit this line) */
