/* Generated By:JJTree: Do not edit this line. ConstructorDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class ConstructorDecl extends SimpleNode {
  public ConstructorDecl(int id) {
    super(id);
  }

  public ConstructorDecl(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ec78e6897f2b238a3b8a92dd6c5632a (do not edit this line) */
