/* Generated By:JJTree: Do not edit this line. ElementValuePairs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class ElementValuePairs extends SimpleNode {
  public ElementValuePairs(int id) {
    super(id);
  }

  public ElementValuePairs(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=89c935d03cbafa344d2088d1d2ba6ba2 (do not edit this line) */
