/* Generated By:JJTree: Do not edit this line. ElementValueArrayInitializer.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class ElementValueArrayInitializer extends SimpleNode {
  public ElementValueArrayInitializer(int id) {
    super(id);
  }

  public ElementValueArrayInitializer(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3f09fbe96250c7fc5a6d144dfe45cf1d (do not edit this line) */
