/* Generated By:JJTree: Do not edit this line. ElementValuePair.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class ElementValuePair extends SimpleNode {
  public ElementValuePair(int id) {
    super(id);
  }

  public ElementValuePair(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=093dae149cb898ed949c34ba2a4f9f00 (do not edit this line) */
