/* Generated By:JJTree: Do not edit this line. EmptyInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class EmptyInterfaceDeclaration extends SimpleNode {
  public EmptyInterfaceDeclaration(int id) {
    super(id);
  }

  public EmptyInterfaceDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2ccd4f9bd1e9e04e4304e161e0dc898c (do not edit this line) */
