/* Generated By:JJTree: Do not edit this line. EnumBodyDeclarations.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class EnumBodyDeclarations extends SimpleNode {
  public EnumBodyDeclarations(int id) {
    super(id);
  }

  public EnumBodyDeclarations(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c625d1cecf0c6147b79930985eac5edf (do not edit this line) */
