/* Generated By:JJTree: Do not edit this line. ExplicitGenericInvocation.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class ExplicitGenericInvocation extends SimpleNode {
  public ExplicitGenericInvocation(int id) {
    super(id);
  }

  public ExplicitGenericInvocation(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8605960149d91a1925b960107f5f7908 (do not edit this line) */
