/* Generated By:JJTree: Do not edit this line. FieldDeclaratorsRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class FieldDeclaratorsRest extends SimpleNode {
  public FieldDeclaratorsRest(int id) {
    super(id);
  }

  public FieldDeclaratorsRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=989bb12c52e50a0f39c365ab488eb346 (do not edit this line) */
