/* Generated By:JJTree: Do not edit this line. FloatingPointLiteral.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class FloatingPointLiteral extends SimpleNode {
  public FloatingPointLiteral(int id) {
    super(id);
  }

  public FloatingPointLiteral(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fe3025fbd17d8bb5bf2f55f6f17a4b43 (do not edit this line) */
