/* Generated By:JJTree: Do not edit this line. FormalParameterDeclsRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class FormalParameterDeclsRest extends SimpleNode {
  public FormalParameterDeclsRest(int id) {
    super(id);
  }

  public FormalParameterDeclsRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3aca5818067595f7c542e8f948dfc038 (do not edit this line) */
