/* Generated By:JJTree: Do not edit this line. FormalParameterDecls.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class FormalParameterDecls extends SimpleNode {
  public FormalParameterDecls(int id) {
    super(id);
  }

  public FormalParameterDecls(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bbaf0ea67a78bf246203cc3550a6b36d (do not edit this line) */
