/* Generated By:JJTree: Do not edit this line. GenericMethodOrConstructorRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class GenericMethodOrConstructorRest extends SimpleNode {
  public GenericMethodOrConstructorRest(int id) {
    super(id);
  }

  public GenericMethodOrConstructorRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=37d7084ef02f93e8769c468e98865530 (do not edit this line) */
