/* Generated By:JJTree: Do not edit this line. HasEllipsis.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class HasEllipsis extends SimpleNode {
  public HasEllipsis(int id) {
    super(id);
  }

  public HasEllipsis(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9ef5d2440c1d558d6f27e1027d49f37b (do not edit this line) */
