/* Generated By:JJTree: Do not edit this line. HasNotStaticModifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class HasNotStaticModifier extends SimpleNode {
  public HasNotStaticModifier(int id) {
    super(id);
  }

  public HasNotStaticModifier(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=4e23cd1adb53b2bfab7b53132258571e (do not edit this line) */
