/* Generated By:JJTree: Do not edit this line. IdentifierSuffix.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class IdentifierSuffix extends SimpleNode {
  public IdentifierSuffix(int id) {
    super(id);
  }

  public IdentifierSuffix(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c4504f04f6d39f42974d7e0736ee5d2f (do not edit this line) */
