/* Generated By:JJTree: Do not edit this line. InterfaceMethodOrFieldRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class InterfaceMethodOrFieldRest extends SimpleNode {
  public InterfaceMethodOrFieldRest(int id) {
    super(id);
  }

  public InterfaceMethodOrFieldRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=0ba56a35ad9ee21da968f29b454bf599 (do not edit this line) */
