/* Generated By:JJTree: Do not edit this line. InterfaceMethodOrFieldDecl.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class InterfaceMethodOrFieldDecl extends SimpleNode {
  public InterfaceMethodOrFieldDecl(int id) {
    super(id);
  }

  public InterfaceMethodOrFieldDecl(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c254f8326d4cb7cc1dcddeb4bdfb5073 (do not edit this line) */
