/* Generated By:JJTree: Do not edit this line. InterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class InterfaceDeclaration extends SimpleNode {
  public InterfaceDeclaration(int id) {
    super(id);
  }

  public InterfaceDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ffaba81eb31532f8220ff47f4f0f7854 (do not edit this line) */
