/* Generated By:JavaCC: Do not edit this line. JavaParser1_7TreeConstants.java Version 5.0 */
package javaparser;

public interface JavaParser1_7TreeConstants
{
  public int JJTIDENTIFIER = 0;
  public int JJTQUALIFIEDIDENTIFIER = 1;
  public int JJTQUALIFIEDIDENTIFIERLIST = 2;
  public int JJTCOMPILATIONUNIT = 3;
  public int JJTIMPORTDECLARATION = 4;
  public int JJTELLIPSIS = 5;
  public int JJTHASELLIPSIS = 6;
  public int JJTHASNOTELLIPSIS = 7;
  public int JJTPOSSIBLESTATICMODIFIER = 8;
  public int JJTHASSTATICMODIFIER = 9;
  public int JJTHASNOTSTATICMODIFIER = 10;
  public int JJTTYPEDECLARATION = 11;
  public int JJTEMPTYINTERFACEDECLARATION = 12;
  public int JJTCLASSORINTERFACEDECLARATION = 13;
  public int JJTMODIFIERLIST = 14;
  public int JJTCLASSDECLARATION = 15;
  public int JJTINTERFACEDECLARATION = 16;
  public int JJTNORMALCLASSDECLARATION = 17;
  public int JJTENUMDECLARATION = 18;
  public int JJTNORMALINTERFACEDECLARATION = 19;
  public int JJTANNOTATIONTYPEDECLARATION = 20;
  public int JJTTYPE = 21;
  public int JJTBASICTYPE = 22;
  public int JJTREFERENCETYPE = 23;
  public int JJTTYPEARGUMENTS = 24;
  public int JJTTYPEARGUMENT = 25;
  public int JJTNONWILDCARDTYPEARGUMENTS = 26;
  public int JJTTYPELIST = 27;
  public int JJTTYPEARGUMENTSORDIAMOND = 28;
  public int JJTNONWILDCARDTYPEARGUMENTSORDIAMOND = 29;
  public int JJTTYPEPARAMETERS = 30;
  public int JJTTYPEPARAMETER = 31;
  public int JJTBOUND = 32;
  public int JJTMODIFIER = 33;
  public int JJTKEYWORDMODIFIER = 34;
  public int JJTANNOTATIONS = 35;
  public int JJTANNOTATION = 36;
  public int JJTANNOTATIONELEMENT = 37;
  public int JJTELEMENTVALUEPAIRS = 38;
  public int JJTELEMENTVALUEPAIR = 39;
  public int JJTELEMENTVALUE = 40;
  public int JJTELEMENTVALUEARRAYINITIALIZER = 41;
  public int JJTELEMENTVALUES = 42;
  public int JJTCLASSBODY = 43;
  public int JJTCLASSBODYDECLARATION = 44;
  public int JJTSTATICINITBLOCK = 45;
  public int JJTMEMBERDECL = 46;
  public int JJTVOIDMETHODDECL = 47;
  public int JJTCONSTRUCTORDECL = 48;
  public int JJTMETHODORFIELDDECL = 49;
  public int JJTMETHODORFIELDREST = 50;
  public int JJTFIELDDECLARATORSREST = 51;
  public int JJTMETHODDECLARATORREST = 52;
  public int JJTMETHODBODY = 53;
  public int JJTEMPTYBODY = 54;
  public int JJTVOIDMETHODDECLARATORREST = 55;
  public int JJTCONSTRUCTORDECLARATORREST = 56;
  public int JJTGENERICMETHODORCONSTRUCTORDECL = 57;
  public int JJTGENERICMETHODORCONSTRUCTORREST = 58;
  public int JJTINTERFACEBODY = 59;
  public int JJTINTERFACEBODYDECLARATION = 60;
  public int JJTNONEMPTYINTERFACEDECLARATION = 61;
  public int JJTINTERFACEMEMBERDECL = 62;
  public int JJTINTERFACEMETHODORFIELDDECL = 63;
  public int JJTINTERFACEMETHODORFIELDREST = 64;
  public int JJTCONSTANTDECLARATORSREST = 65;
  public int JJTCONSTANTDECLARATORREST = 66;
  public int JJTCONSTANTDECLARATOR = 67;
  public int JJTINTERFACEMETHODDECLARATORREST = 68;
  public int JJTVOIDINTERFACEMETHODDECLARATORREST = 69;
  public int JJTINTERFACEGENERICMETHODDECL = 70;
  public int JJTFORMALPARAMETERS = 71;
  public int JJTFORMALPARAMETERDECLS = 72;
  public int JJTVARIABLEMODIFIER = 73;
  public int JJTFORMALPARAMETERDECLSREST = 74;
  public int JJTVARIABLEDECLARATORID = 75;
  public int JJTVARIABLEDECLARATORS = 76;
  public int JJTVARIABLEDECLARATOR = 77;
  public int JJTVARIABLEDECLARATORREST = 78;
  public int JJTVARIABLEINITIALIZER = 79;
  public int JJTARRAYINITIALIZER = 80;
  public int JJTBLOCK = 81;
  public int JJTBLOCKSTATEMENTS = 82;
  public int JJTBLOCKSTATEMENT = 83;
  public int JJTLOCALVARIABLEDECLARATIONSTATEMENT = 84;
  public int JJTSTATEMENT = 85;
  public int JJTEMPTYSTATEMENT = 86;
  public int JJTIDENTIFIERSTATEMENT = 87;
  public int JJTSTATEMENTEXPRESSION = 88;
  public int JJTIFSTATEMENT = 89;
  public int JJTELSESTATEMENT = 90;
  public int JJTNOELSESTATEMENT = 91;
  public int JJTASSERTSTATEMENT = 92;
  public int JJTSWITCHSTATEMENT = 93;
  public int JJTWHILESTATEMENT = 94;
  public int JJTDOSTATEMENT = 95;
  public int JJTFORSTATEMENT = 96;
  public int JJTBREAKSTATEMENT = 97;
  public int JJTLABELEDBREAK = 98;
  public int JJTUNLABELEDBREAK = 99;
  public int JJTCONTINUESTATEMENT = 100;
  public int JJTLABELEDCONTINUE = 101;
  public int JJTUNLABELEDCONTINUE = 102;
  public int JJTRETURNSTATEMENT = 103;
  public int JJTTHROWSTATEMENT = 104;
  public int JJTSYNCHRONIZEDSTATEMENT = 105;
  public int JJTTRYSTATEMENT = 106;
  public int JJTCATCHES = 107;
  public int JJTCATCHCLAUSE = 108;
  public int JJTCATCHTYPE = 109;
  public int JJTFINALLY = 110;
  public int JJTRESOURCESPECIFICATION = 111;
  public int JJTRESOURCES = 112;
  public int JJTRESOURCE = 113;
  public int JJTSWITCHBLOCKSTATEMENTGROUPS = 114;
  public int JJTSWITCHBLOCKSTATEMENTGROUP = 115;
  public int JJTSWITCHLABELS = 116;
  public int JJTSWITCHLABEL = 117;
  public int JJTENUMCONSTANTNAME = 118;
  public int JJTFORCONTROL = 119;
  public int JJTFORVARCONTROL = 120;
  public int JJTFORVARCONTROLREST = 121;
  public int JJTFORVARIABLEDECLARATORSREST = 122;
  public int JJTFORINIT = 123;
  public int JJTFORUPDATE = 124;
  public int JJTEXPRESSION = 125;
  public int JJTEXPRESSIONREST = 126;
  public int JJTASSIGNMENTOPERATOR = 127;
  public int JJTEXPRESSION1 = 128;
  public int JJTEXPRESSION1REST = 129;
  public int JJTEXPRESSION2 = 130;
  public int JJTEXPRESSION2REST = 131;
  public int JJTINFIXOP = 132;
  public int JJTEXPRESSION3 = 133;
  public int JJTPREFIXOP = 134;
  public int JJTPOSTFIXOP = 135;
  public int JJTPRIMARY = 136;
  public int JJTLITERAL = 137;
  public int JJTINTEGERLITERAL = 138;
  public int JJTFLOATINGPOINTLITERAL = 139;
  public int JJTCHARACTERLITERAL = 140;
  public int JJTSTRINGLITERAL = 141;
  public int JJTBOOLEANLITERAL = 142;
  public int JJTNULLLITERAL = 143;
  public int JJTPAREXPRESSION = 144;
  public int JJTARGUMENTS = 145;
  public int JJTSUPERSUFFIX = 146;
  public int JJTEXPLICITGENERICINVOCATIONSUFFIX = 147;
  public int JJTCREATOR = 148;
  public int JJTCREATEDNAME = 149;
  public int JJTCLASSCREATORREST = 150;
  public int JJTARRAYCREATORREST = 151;
  public int JJTIDENTIFIERSUFFIX = 152;
  public int JJTEXPLICITGENERICINVOCATION = 153;
  public int JJTINNERCREATOR = 154;
  public int JJTSELECTOR = 155;
  public int JJTENUMBODY = 156;
  public int JJTENUMCONSTANTS = 157;
  public int JJTENUMCONSTANT = 158;
  public int JJTENUMBODYDECLARATIONS = 159;
  public int JJTANNOTATIONTYPEBODY = 160;
  public int JJTANNOTATIONTYPEELEMENTDECLARATIONS = 161;
  public int JJTANNOTATIONTYPEELEMENTDECLARATION = 162;
  public int JJTANNOTATIONTYPEELEMENTREST = 163;
  public int JJTANNOTATIONMETHODORCONSTANTREST = 164;
  public int JJTANNOTATIONMETHODREST = 165;


  public String[] jjtNodeName = {
    "Identifier",
    "QualifiedIdentifier",
    "QualifiedIdentifierList",
    "CompilationUnit",
    "ImportDeclaration",
    "Ellipsis",
    "HasEllipsis",
    "HasNotEllipsis",
    "PossibleStaticModifier",
    "HasStaticModifier",
    "HasNotStaticModifier",
    "TypeDeclaration",
    "EmptyInterfaceDeclaration",
    "ClassOrInterfaceDeclaration",
    "ModifierList",
    "ClassDeclaration",
    "InterfaceDeclaration",
    "NormalClassDeclaration",
    "EnumDeclaration",
    "NormalInterfaceDeclaration",
    "AnnotationTypeDeclaration",
    "Type",
    "BasicType",
    "ReferenceType",
    "TypeArguments",
    "TypeArgument",
    "NonWildcardTypeArguments",
    "TypeList",
    "TypeArgumentsOrDiamond",
    "NonWildcardTypeArgumentsOrDiamond",
    "TypeParameters",
    "TypeParameter",
    "Bound",
    "Modifier",
    "KeywordModifier",
    "Annotations",
    "Annotation",
    "AnnotationElement",
    "ElementValuePairs",
    "ElementValuePair",
    "ElementValue",
    "ElementValueArrayInitializer",
    "ElementValues",
    "ClassBody",
    "ClassBodyDeclaration",
    "StaticInitBlock",
    "MemberDecl",
    "VoidMethodDecl",
    "ConstructorDecl",
    "MethodOrFieldDecl",
    "MethodOrFieldRest",
    "FieldDeclaratorsRest",
    "MethodDeclaratorRest",
    "MethodBody",
    "EmptyBody",
    "VoidMethodDeclaratorRest",
    "ConstructorDeclaratorRest",
    "GenericMethodOrConstructorDecl",
    "GenericMethodOrConstructorRest",
    "InterfaceBody",
    "InterfaceBodyDeclaration",
    "NonEmptyInterfaceDeclaration",
    "InterfaceMemberDecl",
    "InterfaceMethodOrFieldDecl",
    "InterfaceMethodOrFieldRest",
    "ConstantDeclaratorsRest",
    "ConstantDeclaratorRest",
    "ConstantDeclarator",
    "InterfaceMethodDeclaratorRest",
    "VoidInterfaceMethodDeclaratorRest",
    "InterfaceGenericMethodDecl",
    "FormalParameters",
    "FormalParameterDecls",
    "VariableModifier",
    "FormalParameterDeclsRest",
    "VariableDeclaratorId",
    "VariableDeclarators",
    "VariableDeclarator",
    "VariableDeclaratorRest",
    "VariableInitializer",
    "ArrayInitializer",
    "Block",
    "BlockStatements",
    "BlockStatement",
    "LocalVariableDeclarationStatement",
    "Statement",
    "EmptyStatement",
    "IdentifierStatement",
    "StatementExpression",
    "IfStatement",
    "ElseStatement",
    "NoElseStatement",
    "AssertStatement",
    "SwitchStatement",
    "WhileStatement",
    "DoStatement",
    "ForStatement",
    "BreakStatement",
    "LabeledBreak",
    "UnlabeledBreak",
    "ContinueStatement",
    "LabeledContinue",
    "UnlabeledContinue",
    "ReturnStatement",
    "ThrowStatement",
    "SynchronizedStatement",
    "TryStatement",
    "Catches",
    "CatchClause",
    "CatchType",
    "Finally",
    "ResourceSpecification",
    "Resources",
    "Resource",
    "SwitchBlockStatementGroups",
    "SwitchBlockStatementGroup",
    "SwitchLabels",
    "SwitchLabel",
    "EnumConstantName",
    "ForControl",
    "ForVarControl",
    "ForVarControlRest",
    "ForVariableDeclaratorsRest",
    "ForInit",
    "ForUpdate",
    "Expression",
    "ExpressionRest",
    "AssignmentOperator",
    "Expression1",
    "Expression1Rest",
    "Expression2",
    "Expression2Rest",
    "InfixOp",
    "Expression3",
    "PrefixOp",
    "PostfixOp",
    "Primary",
    "Literal",
    "IntegerLiteral",
    "FloatingPointLiteral",
    "CharacterLiteral",
    "StringLiteral",
    "BooleanLiteral",
    "NullLiteral",
    "ParExpression",
    "Arguments",
    "SuperSuffix",
    "ExplicitGenericInvocationSuffix",
    "Creator",
    "CreatedName",
    "ClassCreatorRest",
    "ArrayCreatorRest",
    "IdentifierSuffix",
    "ExplicitGenericInvocation",
    "InnerCreator",
    "Selector",
    "EnumBody",
    "EnumConstants",
    "EnumConstant",
    "EnumBodyDeclarations",
    "AnnotationTypeBody",
    "AnnotationTypeElementDeclarations",
    "AnnotationTypeElementDeclaration",
    "AnnotationTypeElementRest",
    "AnnotationMethodOrConstantRest",
    "AnnotationMethodRest",
  };
}
/* JavaCC - OriginalChecksum=20a1cfb37390fe0ce048f320b271ab64 (do not edit this line) */
