/* Generated By:JJTree: Do not edit this line. LabeledBreak.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class LabeledBreak extends SimpleNode {
  public LabeledBreak(int id) {
    super(id);
  }

  public LabeledBreak(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5caf44c8e8f6b824cbf82e573bf3e4a4 (do not edit this line) */
