/* Generated By:JJTree: Do not edit this line. MethodOrFieldRest.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class MethodOrFieldRest extends SimpleNode {
  public MethodOrFieldRest(int id) {
    super(id);
  }

  public MethodOrFieldRest(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=910f82b26e6181609185746669026c88 (do not edit this line) */
