/* Generated By:JJTree: Do not edit this line. NonWildcardTypeArgumentsOrDiamond.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class NonWildcardTypeArgumentsOrDiamond extends SimpleNode {
  public NonWildcardTypeArgumentsOrDiamond(int id) {
    super(id);
  }

  public NonWildcardTypeArgumentsOrDiamond(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5a8751005a01961da9ef9452c7d8e895 (do not edit this line) */
