/* Generated By:JJTree: Do not edit this line. NormalInterfaceDeclaration.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class NormalInterfaceDeclaration extends SimpleNode {
  public NormalInterfaceDeclaration(int id) {
    super(id);
  }

  public NormalInterfaceDeclaration(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fb55266f52f80def402e70803768169e (do not edit this line) */
