/* Generated By:JJTree: Do not edit this line. StaticInitBlock.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class StaticInitBlock extends SimpleNode {
  public StaticInitBlock(int id) {
    super(id);
  }

  public StaticInitBlock(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8e0ab50b8d661b67eb62f78eb932ffb4 (do not edit this line) */
