/* Generated By:JJTree: Do not edit this line. SwitchBlockStatementGroup.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class SwitchBlockStatementGroup extends SimpleNode {
  public SwitchBlockStatementGroup(int id) {
    super(id);
  }

  public SwitchBlockStatementGroup(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e1c0b40f5c9fc05393b987a0ffa96546 (do not edit this line) */
