/* Generated By:JJTree: Do not edit this line. TypeArgumentsOrDiamond.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class TypeArgumentsOrDiamond extends SimpleNode {
  public TypeArgumentsOrDiamond(int id) {
    super(id);
  }

  public TypeArgumentsOrDiamond(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=99c98c70f5e31547748a74a4a2abdd53 (do not edit this line) */
