/* Generated By:JJTree: Do not edit this line. UnlabeledContinue.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=true,NODE_PREFIX=,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package javaparser;

public
class UnlabeledContinue extends SimpleNode {
  public UnlabeledContinue(int id) {
    super(id);
  }

  public UnlabeledContinue(JavaParser1_7 p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(JavaParser1_7Visitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=2fc5d8368f7a48817ea3083e1affe1ab (do not edit this line) */
